[Distribution]
Distribution=opensuse
Release=tumbleweed
Architecture=arm64

[Output]
Format=directory
Output=mkosi.rootfs

[Content]
Bootable=no
RootPassword=147147
WithDocs=True
Packages=
	zypper
    firefox

